### ISSUE TITLE
Error al registrarse

### ISSUE THREAD

**Issue by tbms18** [antBaena/InfoChange#5]
El proceso de registro no funciona correctamente. Al cumplimentar los campos y pulsar el botón de registrarse, el backend no registra correctamente al usuario, aunque en el frontend aparezca que se ha realizado correctamente.
El error puede originarse en el backend o en la base de datos. El backend da la siguiente línea al intentar registrarme:
`[28/5/2024, 17:33:39] [ERROR] Register: Malformed Request`

Probado con la última versión del proyecto, y la última versión de la base de datos.

**Comment by antBaena** [comment]
Fixeado, problema se trataba del nombre de los campos de la base de datos, habia algunos mal puestos en la insersion de los datos. 👍
